services:
  myapp:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file:
      - ./dev.env
    networks:
      - myapp-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - myapp
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
