services:
  java-backend:
    build:
      context: ./Java-Spring-backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    env_file:
      - ./spring.env
    networks:
      - app-network

  react-frontend:
    build:
      context: ./React-Frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    env_file:
      - ./react.env
    networks:
      - app-network

  fast-api:
    build:
      context: ./Fast-API
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file:
      - ./fast.env
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - java-backend
      - fast-api
      - react-frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
