services:
  myapp:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - myapp-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - myapp
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

