version: "3.8"

services:
  web:
    build: .
    container_name: my_app_web
    command: gunicorn -b 0.0.0.0:8000 run:app
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: my_app_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
