version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=dev
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
